(()=>{
'use strict';
const E=window.Outpatient307Engine,D=window.Scale307Data,KEY='cx-white-nurse307-outpatient-v1';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fresh=()=>({config:{start:E.dayAdd(today(),-5),finalEnd:'',asOf:'',catheter:'picc',lastCare:E.dayAdd(today(),-5),portInterval:28},drafts:{},assessments:[],reports:[],alerts:[],pushes:[],watched:{},careHistory:[]});
let s;try{s=JSON.parse(localStorage.getItem(KEY))||fresh()}catch{s=fresh()}
const backStack=[];
let patientReturn='home';
const expandedPlans=new Set();
const viewNames={plan:'院外健康计划',reports:'报告列表',scales:'量表中心',care:'导管维护',doctor:'院外预警工作台'};
function rememberPage(){backStack.push({tab,scroll:root.scrollTop});}
function goBack(){const previous=backStack.pop();if(!previous){window.Project307.navigate(audience==='doctor'?'workbench':patientReturn);return}tab=previous.tab;currentScale=null;render();root.scrollTo(0,previous.scroll);}
let audience='patient';
let tab='plan',currentScale=null,scaleTask='adhoc',reportTask='',reportKind='blood',selectedFile=null,reportValues={},filter='pending';
const root=document.createElement('section');root.id='outpatient307';root.className='screen op307';document.querySelector('.phone').append(root);
const now=()=>s.config.asOf||today(),stamp=()=>new Date().toLocaleString('zh-CN'),uid=prefix=>prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);
function persist(){localStorage.setItem(KEY,JSON.stringify(s));badges();window.dispatchEvent(new Event('outpatient307-change'))}
const levelName={normal:'已记录',attention:'需关注',high:'优先处理',urgent:'立即关注'};
const status=(label,level='')=>`<span class="op-chip ${level}">${esc(label)}</span>`;
function alertAdd(source,id,title,body,level){if(level==='normal')return;const key=source+':'+id;if(s.alerts.some(a=>a.key===key))return;s.alerts.unshift({id:uid('alert'),key,source,sourceId:id,title,body,level,state:'pending',created:stamp(),history:[]})}
function taskDone(t){if(t.type==='lab')return t.kinds.every(k=>s.reports.some(r=>r.taskId===t.id&&r.kind===k));if(t.type==='scale')return t.scales.every(k=>s.assessments.some(r=>r.taskId===t.id&&r.scale===k));if(t.type==='video')return Boolean(s.watched[s.config.catheter]);return false}
function sync(){const tasks=E.plan(s.config);for(const t of tasks){if(t.date<=now()&&!s.pushes.some(p=>p.id===t.id))s.pushes.unshift({id:t.id,title:t.label,date:t.date,created:stamp(),channel:'应用内演示待办'});}persist();return tasks}
function badge(){return s.alerts.filter(a=>a.state!=='closed').length}
function badges(){document.querySelectorAll('[data-op-count]').forEach(el=>el.textContent=badge());document.querySelectorAll('[data-op-home-copy]').forEach(el=>{const pending=E.plan(s.config).filter(t=>t.date<=now()&&!taskDone(t)).length;el.textContent=`${pending} 项到期任务 · ${badge()} 条待处理预警`})}
function open(view='plan'){backStack.length=0;audience=view==='doctor'?'doctor':'patient';filter='pending';patientReturn='home';tab=view;currentScale=null;window.Project307.navigate('outpatient307');sync();render()}
function head(title,desc='307项目 · 院外计划与预警'){return `<div class="op-head"><button data-op="back" class="iconbtn" aria-label="返回${backStack.length?viewNames[backStack.at(-1).tab]:(audience==='doctor'?'主任工作台':patientReturn==='special'?'今日任务与院外照护':'助手首页')}">←</button><div><small>${esc(desc)}</small><h1>${title}</h1></div><span class="op-brand">307</span></div>`}
function render(){root.dataset.opView=tab;if($('#guideTag'))$('#guideTag').textContent=audience==='doctor'?'暖欣 DX · 医生端':'橙欣 CX · 患者端';root.innerHTML=head(tab==='doctor'?(audience==='doctor'?'院外预警工作台':'我的健康提醒'):'院外健康计划')+`<div class="op-tabs">${[['plan','计划'],['reports','报告'],['scales','量表'],['care','导管'],['doctor','预警']].map(([k,v])=>`<button data-op="tab" data-value="${k}" class="${tab===k?'active':''}">${v}${k==='doctor'&&badge()?`<i>${badge()}</i>`:''}</button>`).join('')}</div><div id="op-body"></div>`;const body=$('#op-body');body.innerHTML=({plan:planView,reports:reportsView,scales:scalesView,care:careView,doctor:audience==='doctor'?doctorView:patientAlerts}[tab]||planView)();bind();root.scrollTo(0,0)}
function planIcon(kind){if(['lab','scale','care','video','calendar'].includes(kind)){const asset=kind;return `<img class="op-medical-art" src="assets/medical-illustrations/${asset}.png" alt="" aria-hidden="true" width="68" height="68">`;}const paths={lab:'<path d="M9 3h6M10 3v7l-5 8a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-8V3M8 15h8"/>',scale:'<rect x="5" y="4" width="14" height="17" rx="2"/><path d="M9 3h6v4H9zM9 12h6M9 16h4"/>',care:'<path d="M12 3v18M3 12h18"/><circle cx="12" cy="12" r="9"/>',video:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="m10 9 5 3-5 3z"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4M17 3v4M3 10h18M7 14h3M14 14h3M7 17h3"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[kind]||paths.calendar}</svg>`}
function taskCard(t){const done=taskDone(t),due=t.date<=now();const timing=t.day?`化疗第 ${t.day} 天`:t.type==='scale'?'末次化疗后 21 天':'按计划进行';return `<article class="op-task" data-task-kind="${t.type}" data-task-day="${t.day||'final'}"><div class="op-task-day">${planIcon(t.type)}</div><div><b>${esc(t.label)}</b><small class="op-task-timing">${t.date.slice(5).replace('-','月')}日 · ${timing}</small><p>${done?'本次任务已完成':due?(t.date<now()?'已到期，请安排完成':'今天该完成啦'):'到期后自动推送'}</p>${status(done?'已完成':due?'待完成':'未到期',done?'normal':due?'attention':'')}</div><button data-op="task" data-value="${t.id}" class="op-arrow" aria-label="${done?'查看':'打开'}${esc(t.label)}">›</button></article>`}
function planTasks(tasks){
 const first=tasks.filter(t=>t.type==='lab'&&t.day===5),later=tasks.filter(t=>t.type==='lab'&&t.day!==5);
 const scales=tasks.filter(t=>t.type==='scale'),care=tasks.filter(t=>['care','video'].includes(t.type));
 const due=later.filter(t=>t.date<=now()&&!taskDone(t)).length,done=later.filter(taskDone).length;
 return `<div class="op-section-head"><h2>复查安排</h2><span class="op-section-caption">按治疗日程进行</span></div>${first.map(taskCard).join('')}
 <details class="op-plan-fold" data-plan-fold="routine" ${expandedPlans.has('routine')?'open':''}>
 <summary><span class="op-fold-symbol">${planIcon("calendar")}</span><span class="op-fold-copy"><b>后续复查计划</b><small>第 7—21 天 · ${later.length} 次常规复查</small></span><span class="op-fold-chevron" aria-hidden="true"></span><span class="op-fold-status">${due?`${due} 项待完成`:done===later.length?'全部已完成':'按期提醒'}<span>${done} / ${later.length} 已完成</span></span><span class="op-fold-hint"><span class="when-closed">展开日程</span><span class="when-open">收起日程</span></span></summary>
 <div class="op-fold-content"><p class="op-fold-note">血常规按期复查，化疗第 7、14、21 天同时检查肝功能。</p>${later.map(taskCard).join('')}</div></details>
 <div class="op-section-head"><h2>身体感受评估</h2><span class="op-section-caption">量表随访</span></div>${scales.map(taskCard).join('')}
 <div class="op-section-head"><h2>导管照护</h2><span class="op-section-caption">维护与宣教</span></div>${care.map(taskCard).join('')}`;
}
function planView(){const tasks=E.plan(s.config),due=tasks.filter(t=>t.date<=now()&&!taskDone(t));return `<div class="op-hero"><span>OUTPATIENT CARE</span><h2>离院后，照护继续</h2><p>复查、身体感受与导管护理<br>每一个重要节点，都有提醒。</p><div><strong>${due.length}</strong> 项待完成 <span class="op-sep">/</span> <strong>${badge()}</strong> 条待处理预警</div></div><div class="op-datebar"><b>${now()}</b><span>化疗第 ${Math.max(0,E.days(now(),s.config.start)+1)} 天${s.config.asOf?' · 模拟日期':''}</span></div><details class="op-settings"><summary>计划设置与演示日期</summary><form id="op-config"><label>本周期化疗开始日期（D1）<input name="start" type="date" value="${s.config.start}" required></label><label>末次化疗结束日期（可暂不填）<input name="finalEnd" type="date" value="${s.config.finalEnd}"></label><label>演示日期（留空跟随今天）<input name="asOf" type="date" value="${s.config.asOf}"></label><p>复查按 D1 当天起算；末次治疗结束后 21 天单独计算，不等同于本周期 D21。</p><button class="op-primary">保存计划</button></form><div class="op-inline"><button data-op="jump" data-value="7">体验 D7</button><button data-op="jump" data-value="14">体验 D14</button><button data-op="jump" data-value="final">体验末次结束 +21 天</button></div><small>切换演示日期时会补发到期任务，不重复推送。浏览器关闭时不执行真实后台推送。</small></details>${planTasks(tasks)}${!s.config.finalEnd?'<p class="op-note">尚未填写末次化疗结束日期；六量表评估将在日期确认后排期。</p>':''}<details class="op-rules"><summary>查看计划规则与推送记录</summary><p>D5 / D9 / D11 / D17：血常规<br>D7 / D14 / D21：血常规 + 肝功能<br>D7 / D14：安德森症状评估<br>末次化疗结束后 21 天：六份量表</p>${s.pushes.map(p=>`<p>✓ ${p.date} · ${esc(p.title)}<small>已生成应用内演示待办</small></p>`).join('')}</details>`}
function reportsView(){return `<div class="op-section-head"><h2>报告上传与核对</h2>${status('本地保存')}</div><p class="op-note">支持血常规、肝功能、心电图。图片/PDF 原件保存在此浏览器；Demo 未接入真实 OCR，可粘贴报告文字提取数值或手动核对。</p><div class="op-inline">${[['blood','血常规'],['liver','肝功能'],['ecg','心电图']].map(([k,v])=>`<button data-op="new-report" data-value="${k}">＋ ${v}</button>`).join('')}</div><div id="op-report-editor"></div><h2 class="op-section-title">已归档报告 <small>${s.reports.length} 份</small></h2>${s.reports.length?s.reports.slice().reverse().map(r=>`<article class="op-card"><div class="op-between"><b>${{blood:'血常规',liver:'肝功能',ecg:'心电图'}[r.kind]}</b>${status(levelName[r.risk.level],r.risk.level)}</div><p>${r.date} · ${esc(r.fileName||'手动录入')}<br>${r.demo?'虚构识别样例':'已核对录入'} · ${esc(r.taskLabel||'补充报告')}</p><button data-op="report-detail" data-value="${r.id}">查看报告与预审 →</button></article>`).join(''):'<div class="op-empty">还没有归档报告<br><small>上传后核对结果，异常会进入团队预警队列。</small></div>'}`}
function numField(name,label,v,unit){return `<label>${label}<span class="op-unit">${unit||''}</span><input type="number" min="0" step="any" name="${name}" value="${esc(v??'')}" required></label>`}
function reportEditor(kind,taskId=''){reportKind=kind;reportTask=taskId;selectedFile=null;reportValues={};const r=$('#op-report-editor');r.innerHTML=`<form id="op-report-form" class="op-card op-form"><div class="op-between"><h3>${{blood:'血常规',liver:'肝功能',ecg:'心电图'}[kind]} · 核对结果</h3><button type="button" data-op="cancel-report">收起</button></div><label>关联复查任务<select name="taskId"><option value="">补充报告（不关联任务）</option>${E.plan(s.config).filter(t=>t.type==='lab'&&t.kinds.includes(kind)&&t.date<=now()).map(t=>`<option value="${t.id}" ${t.id===taskId?'selected':''}>${t.date} · ${t.label}</option>`).join('')}</select></label><label>报告日期<input type="date" name="date" value="${now()}" max="${now()}" required></label><label class="op-file">选择图片 / PDF / 文本报告<input type="file" id="op-file" accept="image/*,application/pdf,text/plain"></label><p id="op-file-status" class="op-note">未选择原件，也可仅录入数值演示预警。</p><label>粘贴报告文字<textarea name="reportText" placeholder="例如 WBC 1.2，ANC 0.8；请核对绝对值及单位"></textarea></label><button type="button" data-op="extract">提取文字中的指标</button><div class="op-inline"><button type="button" data-op="report-sample" data-value="normal">载入正常示例</button><button type="button" data-op="report-sample" data-value="risk">载入异常示例</button></div><div class="op-fields">${kind==='blood'?numField('wbc','白细胞 WBC','','×10⁹/L')+numField('anc','中性粒细胞绝对值 ANC','','×10⁹/L')+numField('wbcLLN','WBC 参考下限',3.5,'×10⁹/L')+numField('ancLLN','ANC 参考下限',1.8,'×10⁹/L'):kind==='liver'?numField('alt','ALT','','U/L')+numField('altULN','ALT 参考上限',40,'U/L')+numField('ast','AST','','U/L')+numField('astULN','AST 参考上限',40,'U/L')+numField('tbil','总胆红素','','μmol/L')+numField('tbilULN','胆红素参考上限',21,'μmol/L'):'<label>心电图报告结论<select name="ecg"><option>待复核</option><option>未提示异常</option><option>异常</option></select></label><label>结论原文<textarea name="ecgText" required placeholder="填写原报告结论，交由医生核对"></textarea></label>'}</div><p class="op-note">参考上下限请以原报告为准。ANC 为绝对计数，不能用中性粒细胞百分比代替。</p><div id="op-risk-preview" aria-live="polite"></div><label class="op-check"><input type="checkbox" name="verified" required>已核对数值、单位和参考范围</label><p id="op-report-error" role="alert"></p><button class="op-primary" type="submit">确认保存并自动预审</button></form>`;bindReport();bind();r.scrollIntoView({block:'start'})}
async function fileSave(file,id){if(!file)return;const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('white-nurse307-report-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close()}
async function fileRead(id){return new Promise((resolve,reject)=>{const r=indexedDB.open('white-nurse307-report-files',1);r.onupgradeneeded=()=>r.result.createObjectStore('files');r.onerror=()=>reject(r.error);r.onsuccess=()=>{const db=r.result;const q=db.transaction('files').objectStore('files').get(id);q.onsuccess=()=>{resolve(q.result);db.close()};q.onerror=()=>reject(q.error)}})}
function formReport(){return Object.fromEntries(new FormData($('#op-report-form')))}
function previewRisk(){const r={...formReport(),kind:reportKind};const risk=E.labRisk(r);$('#op-risk-preview').innerHTML=risk.hits.length?`<div class="op-alert urgent"><b>命中立即报告规则</b><p>${risk.hits.join('；')}。请立即联系治疗团队；保存后生成医生端预警。</p></div>`:''}
function bindReport(){const f=$('#op-report-form');f.oninput=previewRisk;$('#op-file').onchange=async e=>{selectedFile=e.target.files[0]||null;reportValues.demo=false;if(!selectedFile)return;if(selectedFile.size>20*1024*1024){selectedFile=null;e.target.value='';$('#op-file-status').textContent='请选择不超过 20 MB 的文件。';return}$('#op-file-status').textContent=selectedFile.name+' · 原件已选择，请核对下方指标。';if(selectedFile.type==='text/plain')f.elements.reportText.value=await selectedFile.text();};f.onsubmit=async e=>{e.preventDefault();const v=formReport(),error=$('#op-report-error');if(v.date>now()){error.textContent='报告日期不能晚于当前演示日期';return}const t=E.plan(s.config).find(t=>t.id===v.taskId);if(t&&v.date<t.date){error.textContent='报告日期早于所关联的复查任务，请选择正确任务或作为补充报告保存。';return}if(reportKind==='blood'&&(Number(v.anc)>Number(v.wbc)||Number(v.wbcLLN)<=0||Number(v.ancLLN)<=0)){error.textContent='请核对数值：ANC 不应大于 WBC，参考下限须大于 0。';return}if(reportKind==='liver'&&['altULN','astULN','tbilULN'].some(k=>Number(v[k])<=0)){error.textContent='参考上限须大于 0。';return}const b=f.querySelector('[type=submit]');b.disabled=true;const r={...v,kind:reportKind,id:uid('report'),created:stamp(),fileName:selectedFile?.name||'',hasFile:Boolean(selectedFile),demo:!!reportValues.demo,taskLabel:t?.label||'',risk:E.labRisk({...v,kind:reportKind})};delete r.verified;try{await fileSave(selectedFile,r.id);s.reports.push(r);alertAdd('report',r.id,r.kind==='blood'?'血常规指标预警':r.kind==='liver'?'肝功能需复核':'心电图需复核',r.risk.hits.join('；')||'报告存在异常或待复核结论，请医生核对原件。',r.risk.level);persist();render();reportDetail(r.id)}catch(err){error.textContent='原件保存失败，请检查浏览器存储后重试。';b.disabled=false}}}
function reportDetail(id){const r=s.reports.find(x=>x.id===id);if(!r)return;tab='reports';render();const grades=r.kind==='blood'?`<div class="op-score-grid"><div><b>${r.wbc}</b><small>WBC ×10⁹/L · ${gradeText('wbc',r.wbc,r.wbcLLN)}</small></div><div><b>${r.anc}</b><small>ANC ×10⁹/L · ${gradeText('anc',r.anc,r.ancLLN)}</small></div></div>`:r.kind==='liver'?`<p>ALT：${r.alt} U/L（上限 ${r.altULN}）<br>AST：${r.ast} U/L（上限 ${r.astULN}）<br>总胆红素：${r.tbil} μmol/L（上限 ${r.tbilULN}）</p>`:`<p>${esc(r.ecg)} · ${esc(r.ecgText)}</p>`;
 $('#op-report-editor').innerHTML=`<article class="op-card"><div class="op-between"><h3>报告预审结果</h3>${status(levelName[r.risk.level],r.risk.level)}</div><p>${r.date} · ${r.demo?'虚构样例':'核对录入'}</p>${grades}<div class="op-alert ${r.risk.level}">${r.risk.hits.length?'<b>请立即报告医生并寻求针对性指导</b><p>'+r.risk.hits.join('；')+'。已加入医生端预警队列（演示）。</p>':r.risk.level==='attention'?'请由医生核对原始报告。':'未命中本项目阈值；不代表整体检查正常，仍需结合原报告和医生意见。'}</div>${r.hasFile?`<button data-op="view-file" data-value="${r.id}">查看原始附件</button>`:''}<p class="op-note">血细胞计数分级参考 CTCAE 5.0。项目紧急阈值 WBC &lt;1.5 / ANC &lt;1.0 与 CTCAE 分级独立判断。肝功能及心电图仅标记待复核，不自动作诊断。</p>${contactButton(r.risk.level,s.alerts.find(a=>a.sourceId===r.id)?.id||'')}<button data-op="tab" data-value="doctor">查看预警与跟进 →</button></article>`;bind();root.scrollTo(0,0)}
function gradeText(k,v,lln){const g=E.labGrade(k,v,lln);return g?'CTCAE '+g+' 级（计数预分级）':'未达计数降低标准'}
const notes={bfi:'回顾过去 24 小时；0 = 没有疲乏 / 无影响，10 = 极度疲乏 / 极大影响。',gad7:'根据过去 2 周的情况作答，每题选择发生频率。',phq9:'根据过去 2 周的情况作答。此量表用于筛查，不代替专业诊断。',mdasi:'在化疗期间评估症状严重程度；0 = 没有症状，10 = 能想象的最严重程度。第 22–27 题评估生活干扰。',tfi:'根据您的具体情况选择答案；部分题目包含“有时”。',psqi:'仅回顾近一个月的睡眠习惯。实际睡眠时间不等于卧床时间。'};
const ruleText={bfi:'9 题均分，范围 0–10；均分 ≥4 关注，≥7 优先处理。小数按 [0,4)、[4,7)、[7,10] 分段，不四舍五入后分级。',gad7:'7 题相加，0–21；依模板 ≥10 提醒专业评估。',phq9:'9 题相加，0–27；按模板 5 / 10 / 15 / 20 分分层。第9题任意非零回答独立触发立即关注，不受总分限制。',mdasi:'分别计算 1–21、1–13、14–21、22–27 题均分；任一单项 ≥4 关注，≥7 优先处理（项目演示规则）。',tfi:'15 题计分相加，0–15；第1、12、15题反向计分。第9题“有时”0分，第10、11、14题“有时”1分；≥5 关注。',psqi:'按 7 个成分各 0–3 分相加（0–21），不把18题直接相加。依模板分为0–5、6–10、11–15、16–21；>10关注、>15优先处理为项目演示阈值。'};
function scalesView(){const tasks=E.plan(s.config).filter(t=>t.type==='scale');return `<div class="op-hero small"><span>PATIENT REPORTED OUTCOMES</span><h2>把身体的感受，记录下来</h2><p>六份量表 · 自动计分 · 团队关注</p></div>${tasks.map(t=>`<section class="op-card"><div class="op-between"><h3>${t.label}</h3>${status(t.date<=now()?'已推送':'未到期')}</div><p>${t.date}</p>${t.scales.map(id=>scaleRow(id,t)).join('')}</section>`).join('')}${!s.config.finalEnd?'<p class="op-note">末次化疗日期未确认，六量表任务尚未排期。可从下方提前体验，提前体验记录不会算作计划任务完成。</p>':''}<details class="op-rules"><summary>六份量表 · 单独体验与历史</summary>${Object.keys(D).map(id=>scaleRow(id,null)).join('')}</details><h2 class="op-section-title">评估记录与报告</h2>${s.assessments.length?s.assessments.slice().reverse().map(r=>`<button class="op-record" data-op="scale-result" data-value="${r.id}"><span><b>${esc(D[r.scale].name)}</b><small>${r.date} · ${esc(r.taskLabel||'单独体验')}${r.demo?' · 虚构示范':''}</small></span><strong>${fmt(r.result.value)}<small>分 ›</small></strong></button>`).join(''):'<p class="op-empty">完成评估后，报告会显示在这里。</p>'}<div class="op-inline"><button data-op="export-csv">导出评分 CSV</button><button data-op="export-json">导出完整数据 JSON</button></div><details class="op-rules"><summary>计分与预警依据</summary>${Object.keys(D).map(id=>`<p><b>${esc(D[id].name)}</b><br>${ruleText[id]}</p>`).join('')}<a href="规则与来源.md" target="_blank">查看规则说明与来源</a></details>`}
function scaleIcon(id){const asset=id==='mdasi'?'scale':'scale-'+id;return `<img class="op-medical-art" src="assets/medical-illustrations/${asset}.png" alt="" aria-hidden="true" width="48" height="48">`}

function scaleRow(id,t){const taskId=t?.id||'adhoc',r=s.assessments.filter(x=>x.scale===id&&x.taskId===taskId).at(-1),draft=s.drafts[taskId+':'+id];return `<button class="op-scale-row" data-op="scale-open" data-value="${id}" data-task="${taskId}" ${t&&t.date>now()?'disabled':''}><span class="op-scale-icon">${scaleIcon(id)}</span><span><b>${esc(D[id].name)}</b><small>${D[id].questions.length} 题 · ${r?'已完成 · '+fmt(r.result.value)+' 分':draft?'草稿已保存':t&&t.date>now()?'等待到期':'开始评估'}</small></span><i>›</i></button>`}
const fmt=n=>Number.isInteger(n)?String(n):Number(n).toFixed(2);
function optionsFor(id,i){if(['bfi','mdasi'].includes(id))return Array.from({length:11},(_,n)=>[String(n),n]);if(['gad7','phq9'].includes(id))return ['完全不会','好几天','超过1周','几乎每天'].map((x,n)=>[x,n]);if(id==='tfi')return [[ '是',1],['否',0],...([8,9,10,13].includes(i)?[['有时',2]]:[])];if(id==='psqi'){if(i===14)return ['很好','较好','较差','很差'].map((x,n)=>[x,n]);if(i===17)return ['没有困难','有一点困难','比较困难','非常困难'].map((x,n)=>[x,n]);return ['没有','每周不足1次','每周1–2次','每周3次或以上'].map((x,n)=>[x,n]);}return []}
function scaleOpen(id,taskId='adhoc'){tab='scales';currentScale=id;scaleTask=taskId;const r=s.assessments.filter(x=>x.scale===id&&x.taskId===taskId).at(-1);if(r){scaleResult(r.id);return}const draft=s.drafts[taskId+':'+id]||{answers:Array(D[id].questions.length).fill(''),demo:false};s.drafts[taskId+':'+id]=draft;
 root.innerHTML=head(D[id].name,'量表评估 · 草稿自动保存')+`<button class="op-link" data-op="tab" data-value="scales">← 返回量表中心</button><div class="op-scale-intro"><p>${notes[id]}</p><div class="op-between"><span id="op-progress-text"></span><small>${taskId==='adhoc'?'单独体验':'计划任务'}</small></div><progress id="op-progress" max="${D[id].questions.length}"></progress></div><form id="op-scale-form">${D[id].questions.map((q,i)=>{let input;if(id==='psqi'&&[0,1,2,3].includes(i))input=`<input name="q${i}" aria-label="${esc(q)}" type="${[0,2].includes(i)?'time':'number'}" ${[1,3].includes(i)?`min="0" max="${i===1?1440:24}" step="any"`:''} value="${esc(draft.answers[i])}" required>${i===1?' 分钟':i===3?' 小时':''}`;else input=`<div class="op-options ${['bfi','mdasi'].includes(id)?'numeric':''}">${optionsFor(id,i).map(([label,value])=>`<label><input type="radio" name="q${i}" value="${value}" ${String(draft.answers[i])===String(value)?'checked':''} required><span>${label}</span></label>`).join('')}</div>`;return `<fieldset class="op-question"><legend><em>${i+1}</em>${esc(q)}</legend>${input}${id==='mdasi'&&i>=21?'<small>0 无干扰 — 10 严重干扰</small>':''}</fieldset>`}).join('')}<div class="op-scale-submit"><p id="op-scale-error" role="alert"></p><div id="op-safety-note"></div><button class="op-primary">提交并生成评估报告</button><button type="button" data-op="tab" data-value="scales">保存并稍后继续</button><details><summary>演示快捷填入</summary><p>填入虚构答案用于展示，不会自动提交。</p><button type="button" data-op="scale-sample" data-value="normal">正常样例</button><button type="button" data-op="scale-sample" data-value="risk">异常样例</button></details></div></form>`;
 const f=$('#op-scale-form');function capture(){draft.answers=D[id].questions.map((_,i)=>f.elements['q'+i].value);persist();progress();}
 function progress(){const count=draft.answers.filter(v=>v!==''&&v!=null).length;$('#op-progress').value=count;$('#op-progress-text').textContent=`已完成 ${count} / ${D[id].questions.length} 题`;if(id==='phq9'&&Number(draft.answers[8])>0){$('#op-safety-note').innerHTML='<div class="op-alert urgent">您在第9题提到了伤害自己的念头。请尽快联系医疗团队或可信任的人陪伴；如果有立即伤害自己的危险，请立即呼叫急救或前往急诊。</div>';alertAdd('draft',taskId+':phq9','心理安全回答需立即关注','PHQ-9 第9题出现非零回答（量表未提交，需团队核实）。','urgent');persist();}}
 f.oninput=capture;f.onchange=capture;f.onsubmit=e=>{e.preventDefault();capture();const error=E.validateScale(id,draft.answers);if(error){$('#op-scale-error').textContent=error;return}const result=E.score(id,draft.answers),t=E.plan(s.config).find(t=>t.id===taskId),record={id:uid('assessment'),scale:id,taskId,taskLabel:t?.label||'单独体验',date:now(),created:stamp(),answers:[...draft.answers],demo:draft.demo,result};s.assessments.push(record);delete s.drafts[taskId+':'+id];const draftAlert=id==='phq9'?s.alerts.find(a=>a.key==='draft:'+taskId+':phq9'):null;if(draftAlert){draftAlert.source='scale';draftAlert.sourceId=record.id;draftAlert.state='pending';draftAlert.body='第9题曾出现非零回答；完整量表已提交，请结合本次报告进行人工心理安全评估。';}else alertAdd('scale',record.id,D[id].name+' · '+result.label,result.urgent?'第9题非零回答：请立即进行人工心理安全评估。':`评分 ${fmt(result.value)}，${result.label}。`,result.level);persist();scaleResult(record.id)};progress();bind();root.scrollTo(0,0)}
function sampleScale(kind){const id=currentScale,draft=s.drafts[scaleTask+':'+id];let a;if(id==='psqi')a=kind==='normal'?['22:00',10,'06:00',7.5,...Array(14).fill(0)]:['23:00',70,'06:00',4,...Array(14).fill(3)];else if(id==='tfi')a=Array.from({length:15},(_,i)=>[0,11,14].includes(i)?kind==='normal'?1:0:kind==='normal'?0:1);else a=Array(D[id].questions.length).fill(kind==='normal'?0:['bfi','mdasi'].includes(id)?7:2);draft.answers=a.map(String);draft.demo=true;persist();scaleOpen(id,scaleTask)}
function resultHTML(r){return `<div class="op-result ${r.result.level}"><span>${r.demo?'虚构演示评估':'本次评估结果'}</span><h2>${fmt(r.result.value)}<small> 分</small></h2><b>${esc(r.result.label)}</b><p>${esc(D[r.scale].name)} · ${r.date}</p></div><div class="op-card"><h3>维度评分</h3>${r.result.details.length?r.result.details.map(([k,v])=>`<div class="op-result-row"><span>${k}</span><b>${fmt(v)}</b></div>`).join(''):`<p>总分 ${r.result.value} 分</p>`}<p class="op-note">${ruleText[r.scale]}</p></div><div class="op-alert ${r.result.level}">${r.result.urgent?'第9题已触发立即关注。请尽快联系医疗团队或可信任的人陪伴；若有立即危险，请呼叫急救或前往急诊。':r.result.level!=='normal'?'已生成团队预警（演示），等待医生或护士进一步评估。':'本次未命中项目预警阈值。若身体或情绪有不适，仍可联系团队。'}</div>${contactButton(r.result.level,s.alerts.find(a=>a.sourceId===r.id)?.id||'')}<p class="op-note">筛查结果不构成临床诊断或用药建议。${r.demo?'答案由虚构示范填入。':''}</p>`}
function scaleResult(id){const r=s.assessments.find(x=>x.id===id);if(!r)return;currentScale=null;root.innerHTML=head('量表评估报告')+resultHTML(r)+`<div class="op-inline"><button data-op="download-report" data-value="${r.id}">下载评估报告</button><button data-op="tab" data-value="scales">返回量表中心</button></div><details class="op-rules"><summary>查看逐题答案</summary>${D[r.scale].questions.map((q,i)=>`<p>${i+1}. ${esc(q)}<br><b>${esc(answerLabel(r.scale,i,r.answers[i]))}</b></p>`).join('')}</details>`;bind();root.scrollTo(0,0)}
function answerLabel(id,i,v){return optionsFor(id,i).find(x=>String(x[1])===String(v))?.[0]??String(v)}
function careView(){const c=s.config,due=E.plan(c).find(t=>t.type==='care');return `<div class="op-hero small"><span>LINE CARE</span><h2>让每一次维护，如期完成</h2><p>导管维护提醒与日常观察</p></div><form id="op-care-config" class="op-card op-form"><label>导管类型<select name="catheter"><option value="none" ${c.catheter==='none'?'selected':''}>无导管</option><option value="picc" ${c.catheter==='picc'?'selected':''}>PICC</option><option value="port" ${c.catheter==='port'?'selected':''}>输液港</option></select></label><label>最近一次维护日期<input name="lastCare" type="date" max="${now()}" value="${c.lastCare}" required></label><label>输液港维护间隔（天）<input name="portInterval" type="number" min="1" max="365" value="${c.portInterval}" required></label><small>治疗间歇期默认 4 周（28 天）；若产品说明书另有规定，请由团队确认间隔。</small><button class="op-primary">保存维护设置</button></form>${c.catheter==='none'?'<p class="op-empty">当前无导管，不生成导管维护任务。</p>':`<section class="op-card"><div class="op-between"><h3>下次维护</h3>${status(due&&due.date<=now()?'已到期':'已安排','attention')}</div><h2>${due?.date||'待确认'}</h2><p>${c.catheter==='picc'?'PICC 正常维护间隔不超过 7 天；敷料渗液、潮湿、松动或污染时及时联系维护门诊更换。':'输液港按 4 周或产品说明书维护，由专业人员操作，防止堵塞与感染。'}</p><form id="op-care-done"><label>实际完成日期<input type="date" name="date" value="${now()}" max="${now()}" required></label><button class="op-primary">记录已在门诊完成维护</button></form></section><section class="op-card"><h3>导管维护宣教视频</h3><p>自动推送 · 依据所选导管类型展示</p><video id="op-care-video" controls playsinline preload="metadata" poster="assets/care-${c.catheter}.jpg" src="assets/care-${c.catheter}.mp4"></video><p class="op-note">${s.watched[c.catheter]?'已完成观看 · '+s.watched[c.catheter]:'看完后自动记录学习完成。'}<br>演示动画，不替代专业人员的维护操作。</p></section><section class="op-card"><h3>敷料或导管异常反馈</h3><p>发现渗液、潮湿、松动、污染，或导管堵塞、局部红肿疼痛等情况，请联系团队，不自行处理导管。</p><form id="op-care-issue"><label>异常情况<select name="issue"><option>敷料渗液 / 潮湿</option><option>敷料松动 / 污染</option><option>导管堵塞或疑似移位</option><option>局部红肿疼痛或其他不适</option></select></label><button class="op-primary">报告异常并通知团队（演示）</button></form></section>`}<h2 class="op-section-title">维护记录</h2>${s.careHistory.map(r=>`<div class="op-card"><b>${r.date} · ${r.catheter==='picc'?'PICC':'输液港'}</b><p>患者确认已在门诊完成维护<br>下次到期：${r.next}</p></div>`).join('')||'<p class="op-note">暂无维护记录。</p>'}`}
function contactButton(level,id=''){return audience==='patient'&&level!=='normal'?`<button class="op-primary" data-op="patient-contact" data-value="${id}">立即联系医护团队</button>`:''}
function patientAlerts(){const pending=s.alerts.filter(a=>a.state!=='closed');return `<div class="op-hero"><span>CARE TEAM · 307</span><h2>我的健康提醒</h2><p>查看检查结果与团队跟进情况</p><div><strong>${pending.filter(a=>a.level==='urgent').length}</strong> 条立即关注 <span class="op-sep">/</span><strong>${pending.length}</strong> 条待跟进</div></div>${[...s.alerts].sort((a,b)=>({urgent:0,high:1,attention:2}[a.level]-{urgent:0,high:1,attention:2}[b.level])).map(a=>`<article class="op-card op-risk ${a.level}"><div class="op-between">${status(levelName[a.level],a.level)}${status(a.state==='closed'?'团队已处理':a.state==='contacted'?'团队已联系':'等待团队跟进')}</div><h3>${esc(a.title)}</h3><p>${esc(a.body)}</p>${a.state!=='closed'?contactButton(a.level,a.id):''}${['report','scale'].includes(a.source)?`<button data-op="source" data-value="${a.id}">查看检查与评估记录</button>`:''}</article>`).join('')||'<p class="op-empty">暂无需要跟进的健康提醒</p>'}`}
function contactTeam(id){const a=s.alerts.find(a=>a.id===id);root.querySelector('#op-contact-panel')?.remove();$('#op-body').insertAdjacentHTML('afterbegin',`<section id="op-contact-panel" class="op-card"><h3>联系 307医院白护士长团队</h3><p>${a?esc(a.title):'请向团队说明检查结果与当前身体感受。'}</p><p>请使用您已有的医院联系方式联系医护团队。本 Demo 未接入真实电话或消息。</p><label>补充说明<textarea id="op-contact-note" placeholder="描述希望团队了解的情况（演示）"></textarea></label><button class="op-primary" data-op="request-contact" data-value="${id}">模拟提交联系请求</button><button data-op="dismiss-contact">取消</button></section>`);bind();root.scrollTo(0,0)}
function doctorView(){const all=s.alerts.filter(a=>filter==='all'||(filter==='pending'?a.state!=='closed':a.state==='closed')).sort((a,b)=>({urgent:0,high:1,attention:2}[a.level]-{urgent:0,high:1,attention:2}[b.level]));return `<div class="op-hero doctor"><span>CARE TEAM · DX</span><h2>院外预警工作台</h2><p>演示患者 · 307-001<br>报告与量表异常，在这里跟进。</p><div><strong>${s.alerts.filter(a=>a.state!=='closed'&&a.level==='urgent').length}</strong> 条立即关注 <span class="op-sep">/</span> <strong>${badge()}</strong> 条待处理</div></div><div class="op-inline">${[['pending','待处理'],['closed','已闭环'],['all','全部']].map(([k,v])=>`<button data-op="filter" data-value="${k}" class="${filter===k?'selected':''}">${v}</button>`).join('')}</div>${all.length?all.map(a=>`<article class="op-card op-risk ${a.level}"><div class="op-between">${status(levelName[a.level],a.level)}${status(a.state==='closed'?'已闭环':a.state==='contacted'?'已联系':'待处理')}</div><h3>${esc(a.title)}</h3>${a.contactRequested?'<p class="op-alert attention">患者已请求联系，请及时跟进。</p>':''}<p>${esc(a.body)}</p><small>${esc(a.created)} · ${a.source==='report'?'报告预审':a.source==='care'?'导管反馈':'量表筛查'}</small><div class="op-inline">${['scale','report'].includes(a.source)?`<button data-op="source" data-value="${a.id}">查看原始记录</button>`:''}${a.state!=='closed'?`<button data-op="contact" data-value="${a.id}">标记已联系</button>`:''}</div>${a.state!=='closed'?`<form class="op-resolve" data-alert="${a.id}"><label>处理记录<textarea name="note" required placeholder="记录核对、联系与后续安排（演示）"></textarea></label><button class="op-primary">保存处理记录并闭环</button></form>`:''}${a.history.length?`<details><summary>处理留痕 ${a.history.length} 条</summary>${a.history.map(h=>`<p>${esc(h.time)}<br>${esc(h.text)}</p>`).join('')}</details>`:''}</article>`).join(''):'<div class="op-empty">当前没有此类预警<br><small>患者提交异常报告或量表后，预警会自动进入此处。</small></div>'}<h2 class="op-section-title">数据与研究导出</h2><div class="op-inline"><button data-op="export-csv">评分 CSV</button><button data-op="export-json">完整数据 JSON</button><button data-op="export-alerts">预警 CSV</button></div><p class="op-note">导出包含原始答案、维度分数、采集日期和处理留痕；附件原件不包含在 JSON 中。本页面为同一浏览器内的医生端演示，无真实外发。</p><button data-op="workbench">返回主任工作台</button>`}
function download(name,content,type){
 const url=URL.createObjectURL(new Blob([content],{type}));root.querySelector('.op-export')?.remove();const panel=document.createElement('section');panel.className='op-card op-export';panel.innerHTML=`<h3>导出文件已生成</h3><p>${esc(name)}</p><a class='op-download' href='${url}' download='${esc(name)}'>下载文件</a><p class='op-note'>若当前预览浏览器未弹出下载，可复制下方内容保存为同名文件。</p><textarea readonly aria-label='导出内容'>${esc(content)}</textarea><button type='button'>关闭导出预览</button>`;root.append(panel);panel.querySelector('button').onclick=()=>{URL.revokeObjectURL(url);panel.remove()};panel.scrollIntoView({block:'start'});
}
function exportCSV(){const rows=[['记录ID','患者','任务','量表','评估日期','总分','分层','预警','虚构样例','计分版本','维度分数']];s.assessments.forEach(r=>rows.push([r.id,'307-001',r.taskLabel,D[r.scale].name,r.date,r.result.value,r.result.label,r.result.level,r.demo?'是':'否',r.result.version,JSON.stringify(r.result.details)]));download('307项目-量表评分.csv',E.csv(rows),'text/csv;charset=utf-8')}
function reportDownload(id){const r=s.assessments.find(x=>x.id===id);if(!r)return;download('307项目-'+D[r.scale].name+'-'+r.date+'.html',`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>307项目评估报告</title><style>body{font:16px/1.8 system-ui;max-width:850px;margin:40px auto;padding:24px;color:#34302e}h1{color:#ad6c4c}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:8px}small{color:#777}@media print{body{margin:0}}</style><h1>307项目 · 量表评估报告</h1><p>演示患者 307-001 · ${esc(r.date)} · ${esc(r.taskLabel||'单独体验')} · ${r.demo?'虚构示范答案':'填写记录'}</p>${resultHTML(r)}<h2>逐题答案</h2><table><tr><th>题目</th><th>回答</th></tr>${D[r.scale].questions.map((q,i)=>`<tr><td>${i+1}. ${esc(q)}</td><td>${esc(answerLabel(r.scale,i,r.answers[i]))}</td></tr>`).join('')}</table><p>来源：${esc(D[r.scale].source)}<br>计分版本：${r.result.version}</p></html>`,'text/html;charset=utf-8')}
function bind(){root.querySelectorAll('[data-plan-fold]').forEach(el=>el.ontoggle=()=>{if(el.open)expandedPlans.add(el.dataset.planFold);else expandedPlans.delete(el.dataset.planFold)});root.querySelectorAll('[data-op]').forEach(b=>b.onclick=()=>action(b.dataset.op,b.dataset.value,b.dataset.task));$('#op-config')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));if(v.finalEnd&&v.finalEnd<v.start){window.Project307.toast('末次化疗结束日期不能早于本周期开始日期');return}s.config={...s.config,...v};sync();render()});$('#op-care-config')?.addEventListener('submit',e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));s.config={...s.config,...v};sync();render()});$('#op-care-done')?.addEventListener('submit',e=>{e.preventDefault();const date=new FormData(e.target).get('date');if(date<s.config.lastCare||date>now()){window.Project307.toast('请核对维护日期');return}s.config.lastCare=date;s.careHistory.unshift({date,catheter:s.config.catheter,next:E.dayAdd(date,s.config.catheter==='picc'?7:Number(s.config.portInterval))});sync();render()});$('#op-care-issue')?.addEventListener('submit',e=>{e.preventDefault();const issue=new FormData(e.target).get('issue');alertAdd('care',uid('care'),s.config.catheter.toUpperCase()+' · '+issue,'请联系导管维护门诊，按医护人员指导及时处理。','high');persist();tab='doctor';render()});const video=$('#op-care-video');if(video)video.onended=()=>{s.watched[s.config.catheter]=stamp();persist();window.Project307.toast('宣教视频已看完，学习记录已保存。')};root.querySelectorAll('.op-resolve').forEach(f=>f.onsubmit=e=>{e.preventDefault();const note=new FormData(f).get('note').trim();if(!note)return;const a=s.alerts.find(x=>x.id===f.dataset.alert);a.state='closed';a.history.push({time:stamp(),text:note});persist();render()})}
async function action(op,value,task){if(op==='patient-contact'){contactTeam(value);return}if(op==='dismiss-contact'){$('#op-contact-panel')?.remove();return}if(op==='request-contact'){const a=s.alerts.find(x=>x.id===value);if(a){a.contactRequested=true;a.history.push({time:stamp(),text:'患者请求团队联系（演示）：'+($('#op-contact-note').value.trim()||'请协助核对异常结果')});persist()}$('#op-contact-panel').innerHTML='<h3>联系请求已记录（演示）</h3><p>医生端可看到这条请求；未拨打电话或发送真实消息，请通过医院已有联系方式联系团队。</p>';return}if(['contact','filter'].includes(op)&&audience!=='doctor')return;if(op==='back'){goBack();return}if(op==='home'){window.Project307.navigate('home');return}if(op==='workbench'){window.Project307.navigate('workbench');return}if(op==='tab'){backStack.length=0;tab=value;currentScale=null;render();return}if(op==='jump'){if(value==='final'){if(!s.config.finalEnd)s.config.finalEnd=s.config.start;s.config.asOf=E.dayAdd(s.config.finalEnd,21)}else s.config.asOf=E.dayAdd(s.config.start,Number(value)-1);sync();render();return}if(op==='task'){const t=E.plan(s.config).find(t=>t.id===value);if(!t)return;if(t.date>now()){window.Project307.toast('此任务尚未到期，可用演示日期体验。');return}rememberPage();if(t.type==='lab'){tab='reports';render();const k=t.kinds.find(k=>!s.reports.some(r=>r.taskId===t.id&&r.kind===k));if(k)reportEditor(k,t.id);else reportDetail(s.reports.find(r=>r.taskId===t.id).id)}else {tab=t.type==='scale'?'scales':'care';render();}return}
 if(op==='new-report'){reportEditor(value);return}if(op==='cancel-report'){$('#op-report-editor').innerHTML='';return}if(op==='report-sample'){const f=$('#op-report-form');selectedFile=null;f.elements['op-file'].value='';reportValues.demo=true;const normal=value==='normal';const vals=reportKind==='blood'?{wbc:normal?5.2:1.2,anc:normal?3.1:.8}:reportKind==='liver'?{alt:normal?20:98,ast:normal?22:75,tbil:normal?12:32}:{ecg:normal?'未提示异常':'异常',ecgText:normal?'虚构示例：窦性心律，未提示明显异常。':'虚构示例：报告提示心电图异常，请医生结合原图复核。'};Object.entries(vals).forEach(([k,v])=>f.elements[k].value=v);$('#op-file-status').textContent='已载入虚构识别样例，无真实附件。请核对后保存。';previewRisk();return}
 if(op==='extract'){const f=$('#op-report-form'),text=f.elements.reportText.value;reportValues.demo=false;const map=reportKind==='blood'?{wbc:/(?:WBC|白细胞(?:计数)?)\s*[:：=]?\s*(\d+(?:\.\d+)?)/i,anc:/(?:ANC|NEUT#|中性粒细胞绝对(?:值|计数))\s*[:：=]?\s*(\d+(?:\.\d+)?)/i}:{alt:/(?:ALT|丙氨酸氨基转移酶)\s*[:：=]?\s*(\d+(?:\.\d+)?)/i,ast:/(?:AST|天门冬氨酸氨基转移酶)\s*[:：=]?\s*(\d+(?:\.\d+)?)/i,tbil:/(?:TBIL|总胆红素)\s*[:：=]?\s*(\d+(?:\.\d+)?)/i};let found=0;if(reportKind==='ecg'){f.elements.ecgText.value=text;f.elements.ecg.value='待复核';found=text?1:0}else Object.entries(map).forEach(([k,re])=>{const m=text.match(re);if(m){f.elements[k].value=m[1];found++}});$('#op-file-status').textContent=`已从粘贴文字提取 ${found} 项，请核对原报告及单位；未识别字段需手动填写。`;previewRisk();return}
 if(op==='report-detail'){rememberPage();reportDetail(value);return}if(op==='view-file'){try{const file=await fileRead(value);if(!file){window.Project307.toast('原始附件不在此浏览器，请重新上传。');return}const url=URL.createObjectURL(file);const r=s.reports.find(x=>x.id===value);$('#op-report-editor').insertAdjacentHTML('beforeend',`<div class="op-card">${file.type.startsWith('image/')?`<img class="op-original" src="${url}" alt="原始报告附件">`:`<a href="${url}" download="${esc(r.fileName)}">下载原始报告</a>`}</div>`);}catch{window.Project307.toast('无法读取原始附件。')}return}
 if(op==='scale-open'){rememberPage();scaleOpen(value,task);return}if(op==='scale-sample'){sampleScale(value);return}if(op==='scale-result'){rememberPage();scaleResult(value);return}if(op==='filter'){filter=value;render();return}if(op==='contact'){const a=s.alerts.find(x=>x.id===value);a.state='contacted';a.history.push({time:stamp(),text:'团队已联系患者（演示）'});persist();render();return}if(op==='source'){rememberPage();const a=s.alerts.find(x=>x.id===value);a.source==='report'?reportDetail(a.sourceId):scaleResult(a.sourceId);return}
 if(op==='download-report'){reportDownload(value);return}if(op==='export-csv'){exportCSV();return}if(op==='export-json'){download('307项目-院外随访数据.json',JSON.stringify({project:'307项目',patient:'307-001（演示）',exported:new Date().toISOString(),...s},null,2),'application/json');return}if(op==='export-alerts'){download('307项目-预警记录.csv',E.csv([['预警ID','来源','标题','等级','状态','生成时间','内容','处理记录'],...s.alerts.map(a=>[a.id,a.source,a.title,a.level,a.state,a.created,a.body,JSON.stringify(a.history)])]),'text/csv;charset=utf-8');return}}
function inject(){
 const entry='<button class="op-home-entry" type="button"><span class="op-home-icon"><img src="assets/medical-illustrations/care-plan.png" alt="" aria-hidden="true"></span><span><b>今日院外照护</b><small data-op-home-copy>复查 · 量表评估 · 导管维护</small></span><i>›</i></button>';
 $('#home .home-bottom').insertAdjacentHTML('beforebegin',entry);
 $('#home .op-home-entry').onclick=()=>window.Project307.navigate('special');
 $('#homeReport').onclick=$('#homeCamera').onclick=()=>open('reports');
 $('#homeCalendar').onclick=()=>open('plan');
}

window.Outpatient307={open,openFromTimeline:view=>{open(view);patientReturn='special'},openAlertsFromTimeline:()=>{open('plan');patientReturn='special';tab='doctor';render()},openTaskFromTimeline:id=>{open('plan');patientReturn='special';action('task',id)},snapshot:()=>({now:now(),config:{...s.config},tasks:E.plan(s.config).map(t=>({...t,done:taskDone(t)})),alerts:s.alerts.filter(a=>a.state!=='closed').map(a=>({...a}))}),openTask:id=>{open('plan');action('task',id)},reset:()=>{backStack.length=0;s=fresh();persist();sync();render()},render,refresh:()=>{sync();if(root.classList.contains('active'))render()}};
inject();sync();render();let lastDate=now();function tick(){sync();if(lastDate!==now()){lastDate=now();if(root.classList.contains('active')&&!currentScale&&!$('#op-report-form'))render()}}window.addEventListener('focus',tick);setInterval(tick,60000);
})();
